#!/usr/bin/env python
#-*- coding: utf-8 -*-

from PIL import Image; #Importation du module image de python
im=Image.open("logo-pernod-51.png");
pixel=img.load();
largeur=img.size[0];
hauteur=img.size[1];
for i in range(largeur):
	for j in range(hauteur):
		rouge,vert,bleu=pixel[i,j];
		pixel([i,j]=rouge,0,0);
img.show();

 
